homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Tallinn
  # Include packages
  packages: !include_dir_named packages
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

lovelace:
  mode: yaml

system_health:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret home_assistant_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

alexa:
  smart_home:

panel_iframe:
  music:
    title: 'Pi Music'
    icon: 'mdi:music-box-outline'
    url: !secret media_player_host_url

mqtt:
  broker: !secret home_assistant_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

# Enables support for tracking state changes over time
history:

recorder:
  purge_keep_days: 3
  auto_purge: true

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Python scripts
python_script:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
    monitored_conditions:
     - temperature
     - symbol
     - humidity
     - cloudiness

  - platform: template
    sensors:
      monitor_status:
        value_template: '{{ states.input_select.monitor_status.state}}'
        friendly_name: 'Monitor Status'

  - platform: history_stats
    name: Fridge Open Today
    entity_id: binary_sensor.fridge
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Hall Door Open Today
    entity_id: binary_sensor.hall_door
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Main Door Open Today
    entity_id: binary_sensor.door
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  # Caused too many state changes disabled for a while
  - platform: history_stats
    name: TV On today
    entity_id: media_player.webos_tv
    state: 'playing'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

fastdotcom:
  scan_interval:
    minutes: 60

wake_on_lan:

media_player:
  - platform: mpd
    host: !secret media_player_host

webostv:
  name: webOS TV
  host: !secret livingroom_tv_host
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret livingroom_mac

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: home-assistant
    platform: telegram
    chat_id: !secret telegram_chat_id

  - name: email
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret email_sender
    encryption: starttls
    username: !secret email_username
    password: !secret email_password
    recipient:
      - !secret email_recipient_first
      - !secret email_recipient_second
    sender_name: Tark Kodu

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
