homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Tallinn
  country: EE
  # Include packages
  packages: !include_dir_named packages
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

lovelace:
  mode: yaml
  dashboards:
    other-lovelace:
      mode: yaml
      filename: other-lovelace.yaml
      title: Other
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true

system_health:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem

# Android/iOS companion app
mobile_app:

# Enables support for tracking state changes over time
history:

recorder:
  purge_keep_days: 3
  auto_purge: true
  exclude:
    entities:
      # Exclude Tasmota status from history
      - sensor.sonoff_bridge_status
      - sensor.sonoff_status_4
      - sensor.sonoff_status_3
      - sensor.sonoff_status_2
      - sensor.blitzwolf_socket_status

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Python scripts
python_script:

# Sensors
sensor:
  - platform: history_stats
    name: TV On today
    entity_id: media_player.webos_tv
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: foxess
    deviceID: !secret foxesscloud_inverter_id
    deviceSN: !secret foxesscloud_device_sn
    apiKey: !secret foxesscloud_api_key

energy:

wake_on_lan:

media_player:
  - platform: mpd
    host: !secret media_player_host

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: home-assistant
    platform: telegram
    chat_id: !secret telegram_chat_id

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
