title: Main dashboard
resources:
  - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /local/community/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /local/community/mini-media-player/mini-media-player-bundle.js
    type: module
views:
  - title: Home
    cards:
      - type: grid
        columns: 1
        square: false
        cards:
          - type: picture-glance
            title: Front
            aspect_ratio: '16:9'
            entities: []
            camera_image: camera.mjpeg_camera
          - type: weather-forecast
            entity: weather.home
          - type: iframe
            aspect_ratio: 100%
            url: 'https://embed.windy.com/embed2.html?rain,59.3543993,26.3667541,8'

      - type: grid
        columns: 2
        square: false
        cards:
          - type: picture-entity
            entity: sensor.rn_status
            image: /local/rhino.jpg
            aspect_ratio: '16x9'
            state_filter:
              "Home": brightness(110%) saturate(1.2)
              "Away": brightness(50%)
              "Extended Away": brightness(50%)
              "Just Left": brightness(50%)

          - type: picture-entity
            entity: sensor.rv_status
            image: /local/tiger.jpg
            aspect_ratio: '16x9'
            state_filter:
              "Home": brightness(110%) saturate(1.2)
              "Away": brightness(50%)
              "Extended Away": brightness(50%)
              "Just Left": brightness(50%)

      - type: vertical-stack
        cards:
        - type: markdown
          content: '### Light'
        - type: grid
          columns: 4
          square: true
          cards:
            - type: button
              tap_action:
                action: toggle
              entity: light.sonoff_stairs_light
              name: Stairs
              show_icon: true
            - type: button
              tap_action:
                action: toggle
              entity: light.bedroom_light
              name: Bedroom
            - type: button
              tap_action:
                action: toggle
              entity: light.sonoff
              name: TV
            - type: button
              tap_action:
                action: toggle
              entity: light.sonoff_second_floor_light
              name: Second floor
            - type: button
              tap_action:
                action: toggle
              entity: light.outdoor_lights
              name: Outdoor
            - type: button
              tap_action:
                action: toggle
              entity: switch.garage_light
              name: Garage
              icon: 'hass:lightbulb'
            - type: button
              tap_action:
                action: toggle
              entity: light.pavilion
              name: Pavilion


        - type: markdown
          content: '### Motion'
        - type: grid
          columns: 4
          square: true
          cards:
            - type: button
              entity: binary_sensor.kitchen_motion
              show_icon: true
              name: Kitchen
            - type: button
              entity: binary_sensor.staircase_motion
              show_icon: true
              name: Stairs
            - type: button
              entity: binary_sensor.xiaomi_motion
              show_icon: true
              name: Middle
            - type: button
              entity: binary_sensor.tradfri_motion_sensor
              show_icon: true
              name: RN Office

        - type: markdown
          content: '### Door/window & other'
        - type: grid
          columns: 4
          square: true
          cards:
            - type: button
              entity: binary_sensor.door_sensor
              show_icon: true
              name: Door
            - type: button
              entity: binary_sensor.hall_door_sensor
              show_icon: true
              name: Hall
            - type: button
              entity: binary_sensor.water_leak
              show_icon: true
              name: Boiler

      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:mini-graph-card
            show:
              fill: false
            align_icon: right
            line_color: red
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.xiaomi_lywsd02_temperature
                name: Living room
          - type: custom:mini-graph-card
            icon: mdi:water-percent
            show:
              fill: false
              name: true
            align_icon: right
            line_color: blue
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.xiaomi_lywsd02_humidity
                name: Humidity

          - type: custom:mini-graph-card
            show:
              fill: false
            align_icon: right
            line_color: red
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.temperature_living_room
                name: Living room - window
          - type: custom:mini-graph-card
            icon: mdi:water-percent
            show:
              fill: false
              name: true
            align_icon: right
            line_color: blue
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.humidity_living_room
                name: Humidity

          - type: custom:mini-graph-card
            show:
              fill: false
            align_icon: right
            line_color: red
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.first_temperature
                name: RN Room
          - type: custom:mini-graph-card
            icon: mdi:water-percent
            show:
              fill: false
              name: true
            align_icon: right
            line_color: blue
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.first_humidity
                name: Humidity

          - type: custom:mini-graph-card
            show:
              fill: false
            align_icon: right
            line_color: red
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.second_temperature
                name: Office
          - type: custom:mini-graph-card
            icon: mdi:water-percent
            show:
              fill: false
              name: true
            align_icon: right
            line_color: blue
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.second_humidity
                name: Humidity

          - type: custom:mini-graph-card
            show:
              fill: false
            align_icon: right
            line_color: red
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.mijia_temperature
                name: Bathroom
          - type: custom:mini-graph-card
            icon: mdi:water-percent
            show:
              fill: false
              name: true
            align_icon: right
            line_color: blue
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.mijia_humidity
                name: Humidity

      - type: grid
        columns: 1
        square: false
        cards:
          - type: 'custom:mini-media-player'
            artwork: material
            entity: media_player.webos_tv
          - type: 'custom:mini-media-player'
            artwork: material
            entity: media_player.risto_s_echo_dot
          - type: 'custom:mini-media-player'
            source: icon
            entity: media_player.mpd
            artwork: material
            hide:
              info: false
              power_state: false
              source: false
              volume: false
            shortcuts:
              buttons:
                - id: 'https://router.euddn.net/8103046e16b71d15d692b57c187875c7/elmar.aac'
                  name: Elmar
                  type: music
                - id: 'https://sky.babahhcdn.com/RETRO'
                  name: Retro FM
                  type: music
                - id: 'https://ice.leviracloud.eu/star96-aac'
                  name: Star FM
                  type: music
                - id: 'https://striiming.trio.ee/myhits.mp3'
                  name: My Hits
                  type: music
                - id: 'https://ice.leviracloud.eu/phr96-aac'
                  name: Power Hit
                  type: music
                - id: Christmas
                  name: Christmas
                  type: playlist
                - id: ''
                  name: Favorite
                  type: music
              columns: 2

      - type: entities
        title: Garbage schedule
        entities:
          - type: attribute
            entity: sensor.garbage_schedule
            attribute: next_visit_day
            format: relative
            icon: mdi:delete-outline
            name: Remaining time
          - type: attribute
            entity: sensor.garbage_schedule
            attribute: next_visit_day
            format: date
            icon: mdi:delete
            name: Next pickup

      - type: entities
        title: Counters
        show_header_toggle: false
        entities:
          # - sensor.fridge_open_today
          - sensor.hall_door_open_today
          - sensor.main_door_open_today
          - sensor.tv_on_today
          # - sensor.pow_energy_today
          - sensor.blitzwolf_socket_energy_today

      - type: custom:mini-graph-card
        entities:
          - entity: sensor.blitzwolf_socket_energy_power
        name: PC energy usage
        icon: mdi:chart-line
        show:
          graph: bar

      # List battery levels
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: Batteries
          show_header_toggle: false
        sort:
          method: state
          reverse: true
        filter:
          include:
            - entity_id: "sensor.*_battery_level"
              state: "< 100"
