title: Main dashboard
resources:
  - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /local/community/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /local/community/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /local/community/apexcharts-card/apexcharts-card.js
    type: module
views:
  - title: Home
    cards:
      - type: grid
        columns: 1
        square: false
        cards:
          - type: picture-glance
            title: Front
            aspect_ratio: '16:9'
            entities: []
            camera_image: camera.mjpeg_camera
          - type: weather-forecast
            entity: weather.home
          - type: iframe
            aspect_ratio: 100%
            url: 'https://embed.windy.com/embed2.html?rain,59.3543993,26.3667541,8'

      - type: grid
        columns: 2
        square: false
        cards:
          - type: picture-entity
            entity: sensor.rn_status
            image: /local/rhino.jpg
            aspect_ratio: '16x9'
            state_filter:
              "Home": brightness(110%) saturate(1.2)
              "Away": brightness(50%)
              "Extended Away": brightness(50%)
              "Just Left": brightness(50%)

          - type: picture-entity
            entity: sensor.rv_status
            image: /local/tiger.jpg
            aspect_ratio: '16x9'
            state_filter:
              "Home": brightness(110%) saturate(1.2)
              "Away": brightness(50%)
              "Extended Away": brightness(50%)
              "Just Left": brightness(50%)

      - type: vertical-stack
        cards:
        - type: markdown
          content: '### Light'
        - type: grid
          columns: 4
          square: true
          cards:
            - type: button
              tap_action:
                action: toggle
              entity: light.sonoff_stairs_light
              name: Stairs
              show_icon: true
            - type: button
              tap_action:
                action: toggle
              entity: light.bedroom_light
              name: Bedroom
            - type: button
              tap_action:
                action: toggle
              entity: light.sonoff
              name: TV
            - type: button
              tap_action:
                action: toggle
              entity: light.sonoff_second_floor_light
              name: Second floor
            - type: button
              tap_action:
                action: toggle
              entity: light.outdoor_lights
              name: Outdoor
            - type: button
              tap_action:
                action: toggle
              entity: switch.garage_light
              name: Garage
              icon: 'hass:lightbulb'
            - type: button
              tap_action:
                action: toggle
              entity: light.pavilion
              name: Pavilion
            - type: button
              tap_action:
                action: toggle
              entity: light.all_rgbw2_lights
              name: Bed LED

        - type: markdown
          content: '### Motion'
        - type: grid
          columns: 4
          square: true
          cards:
            - type: button
              entity: binary_sensor.kitchen_motion
              show_icon: true
              name: Kitchen
            - type: button
              entity: binary_sensor.staircase_motion
              show_icon: true
              name: Stairs
            - type: button
              entity: binary_sensor.xiaomi_motion
              show_icon: true
              name: Middle
            - type: button
              entity: binary_sensor.tradfri_motion_sensor
              show_icon: true
              name: RN Office

        - type: markdown
          content: '### Door/window & other'
        - type: grid
          columns: 4
          square: true
          cards:
            - type: button
              entity: binary_sensor.door_sensor
              show_icon: true
              name: Door
            - type: button
              entity: binary_sensor.hall_door_sensor
              show_icon: true
              name: Hall
            - type: button
              entity: binary_sensor.water_leak
              show_icon: true
              name: Boiler

      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:mini-graph-card
            show:
              fill: false
            align_icon: right
            line_color: red
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.xiaomi_lywsd02_temperature
                name: Living room

          - type: custom:mini-graph-card
            icon: mdi:water-percent
            show:
              fill: false
              name: true
            align_icon: right
            line_color: blue
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.xiaomi_lywsd02_humidity
                name: Humidity

          - type: custom:mini-graph-card
            show:
              fill: false
            align_icon: right
            line_color: red
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.temperature_living_room
                name: Living room - window

          - type: custom:mini-graph-card
            icon: mdi:water-percent
            show:
              fill: false
              name: true
            align_icon: right
            line_color: blue
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.humidity_living_room
                name: Humidity

          - type: custom:mini-graph-card
            show:
              fill: false
            align_icon: right
            line_color: red
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.first_temperature
                name: RN Room
          - type: custom:mini-graph-card
            icon: mdi:water-percent
            show:
              fill: false
              name: true
            align_icon: right
            line_color: blue
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.first_humidity
                name: Humidity

          - type: custom:mini-graph-card
            show:
              fill: false
            align_icon: right
            line_color: red
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.second_temperature
                name: Office
          - type: custom:mini-graph-card
            icon: mdi:water-percent
            show:
              fill: false
              name: true
            align_icon: right
            line_color: blue
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.second_humidity
                name: Humidity

          - type: custom:mini-graph-card
            show:
              fill: false
            align_icon: right
            line_color: red
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.mijia_temperature
                name: Bathroom
          - type: custom:mini-graph-card
            icon: mdi:water-percent
            show:
              fill: false
              name: true
            align_icon: right
            line_color: blue
            line_width: 8
            font_size: 75
            entities:
              - entity: sensor.mijia_humidity
                name: Humidity

      - type: grid
        columns: 1
        square: false
        cards:
          - type: custom:apexcharts-card
            experimental:
              color_threshold: true
            graph_span: 24h
            header:
              title: Nordpool price today (eur/mWh)
              show: true
            span:
              start: day
            now:
              show: true
              label: Now
            series:
              - entity: sensor.nordpool_mwh_ee_eur
                type: column
                data_generator: |
                  return entity.attributes.raw_today.map((start, index) => {
                    return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];
                  });
                color_threshold:
                  - value: 0
                    color: green
                    opacity: 1
                  - value: 150
                    color: yellow
                  - value: 250
                    color: red

          - type: 'custom:apexcharts-card'
            experimental:
              color_threshold: true
            graph_span: 1d
            header:
              title: Nordpool tomorrow (eur/mWh)
              show: true
            span:
              start: day
              offset: +1d
            series:
              - entity: sensor.nordpool_mwh_ee_eur
                type: column
                data_generator: |
                  return entity.attributes.raw_tomorrow.map((start, index) => {
                    return [new Date(start["start"]).getTime(), entity.attributes.raw_tomorrow[index]["value"]];
                  });
                color_threshold:
                  - value: 0
                    color: green
                    opacity: 1
                  - value: 150
                    color: yellow
                  - value: 250
                    color: red
      - type: grid
        columns: 1
        square: false
        cards:
          - type: 'custom:mini-media-player'
            artwork: material
            entity: media_player.webos_tv

      - type: entities
        title: Garbage schedule
        entities:
          - type: attribute
            entity: sensor.garbage_schedule
            attribute: next_visit_day
            format: relative
            icon: mdi:delete-outline
            name: Remaining time
          - type: attribute
            entity: sensor.garbage_schedule
            attribute: next_visit_day
            format: date
            icon: mdi:delete
            name: Next pickup

      - type: entities
        title: Counters
        show_header_toggle: false
        entities:
          # - sensor.fridge_open_today
          - sensor.hall_door_open_today
          - sensor.main_door_open_today
          - sensor.tv_on_today
          # - sensor.pow_energy_today
          - sensor.blitzwolf_socket_energy_today

      - type: custom:mini-graph-card
        entities:
          - entity: sensor.blitzwolf_socket_energy_power
        name: PC energy usage
        icon: mdi:chart-line
        show:
          graph: bar

      # List battery levels
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: Batteries
          show_header_toggle: false
        sort:
          method: state
          reverse: true
        filter:
          include:
            - entity_id: "sensor.*_battery_level"
              state: "< 100"
