
binary_sensor:
  - platform: mqtt
    name: "Fridge"
    state_topic: "sonoff-bridge/tele/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    device_class: "door"
    payload_on: "2CBF0A"
    payload_off: "2CBF0E"
    qos: 1

  - platform: mqtt
    name: "Fridge door battery"
    device_class: "battery"
    state_topic: "sonoff-bridge/tele/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "2CBF06"
    off_delay: 60
    qos: 1

  - platform: mqtt
    name: "Hall door"
    device_class: "door"
    state_topic: "sonoff-bridge/tele/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "2E970A"
    payload_off: "2E970E"
    qos: 1

  - platform: mqtt
    name: "Hall door battery"
    device_class: "battery"
    state_topic: "sonoff-bridge/tele/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "2E9706"
    off_delay: 60
    qos: 1

  - platform: mqtt
    name: "Door"
    device_class: "door"
    state_topic: "sonoff-bridge/tele/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "2F420A"
    payload_off: "2F420E"
    qos: 1

  - platform: mqtt
    name: "Door battery"
    device_class: "battery"
    state_topic: "sonoff-bridge/tele/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "2F4206"
    off_delay: 60
    qos: 1

automation:
  - alias: Turn low battery message notify
    trigger:
    - entity_id: binary_sensor.door_battery, 
        binary_sensor.fridge_door_battery, 
        binary_sensor.hall_door_battery
      from: 'off'
      to: 'on'
      platform: state
    action:
    - service: notify.livingroom_tv
      data:
        message: "Patarei on tühi"
    - service: notify.email
      data:
          title: 'Patarei on tühi'
          message: 'patarei saab tühjaks, kontrolli'

  - alias: Play sound when fridge is open
    trigger:
    - entity_id: binary_sensor.fridge
      from: 'off'
      to: 'on'
      platform: state
    condition:
      condition: and
      conditions:
      - condition: sun
        before: sunset
      - condition: sun
        after: sunrise
    action:
    - service: media_player.play_media
      data:
        entity_id: media_player.mpd
        media_content_type: 'music'
      data_template:
        # TODO: Remove hardcoded host url
        media_content_id: > 
          http://192.168.1.228:8123/local/fridge-{{range(0,6) | random}}.mp3
