
binary_sensor:
  - platform: mqtt
    name: 'Fridge Sensor'
    state_topic: 'home/fridge-door'
    device_class: Door

  - platform: mqtt
    name: 'Fridge door battery'
    device_class: 'battery'
    state_topic: 'home/fridge-door-battery'
    off_delay: 60
    qos: 1

  - platform: mqtt
    name: 'Hall Door Sensor'
    state_topic: 'home/hall-door'
    device_class: Door

  - platform: mqtt
    name: 'Hall door battery'
    device_class: 'battery'
    state_topic: 'home/hall-door-battery'
    off_delay: 60
    qos: 1

  - platform: mqtt
    name: 'Door Sensor'
    state_topic: 'home/door'
    device_class: Door

  - platform: mqtt
    name: 'Door battery'
    device_class: 'battery'
    state_topic: 'home/door-battery'
    off_delay: 60
    qos: 1

sensor:
  - platform: history_stats
    name: Hall Door Open Today
    entity_id: binary_sensor.hall_door_sensor
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: Main Door Open Today
    entity_id: binary_sensor.door_sensor
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

automation:
  - alias: Turn low battery message notify
    trigger:
    - entity_id: binary_sensor.door_battery, 
        binary_sensor.fridge_door_battery, 
        binary_sensor.hall_door_battery
      from: 'off'
      to: 'on'
      platform: state
    action:
    - service: notify.webostv
      data:
        message: 'Patarei on tühi'
    - service: persistent_notification.create
      data:
          title: 'Patarei on tühi'
          message: 'patarei saab tühjaks, kontrolli'

  - alias: Play sound when fridge is open
    trigger:
    - entity_id: binary_sensor.fridge_sensor
      from: 'off'
      to: 'on'
      platform: state
    condition:
      condition: and
      conditions:
      - condition: sun
        before: sunset
      - condition: sun
        after: sunrise
    action:
    - service: media_player.play_media
      data:
        entity_id: media_player.mpd
        media_content_type: 'music'
      data_template:
        # TODO: Remove hardcoded host url
        media_content_id: > 
          http://192.168.1.228:8123/local/fridge-{{range(0,6) | random}}.mp3
