
sensor:
  - platform: mqtt
    name: "Moving PIR"
    state_topic: "home/temperature-sensor-second"
    value_template: '{{ value_json.motion }}'
    qos: 1

binary_sensor:
  - platform: mqtt
    name: "Digoo Motion"
    device_class: motion
    state_topic: "sonoff-bridge/tele/RESULT"
    value_template: "{{value_json.RfReceived.Data}}"
    payload_on: "E28186"
    off_delay: 10
    qos: 1

  - platform: mqtt
    name: "Motion Kitchen"
    device_class: motion
    state_topic: "sonoff-bridge/tele/RESULT"
    value_template: "{{value_json.RfReceived.Data}}"
    payload_on: "037526"
    off_delay: 120
    qos: 1

automation:
  - alias: Turn kitchen light on movement
    trigger:
    - entity_id: binary_sensor.motion_kitchen
      platform: state
      from: 'off'
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: '-02:00:00'
      - condition: sun
        before: sunrise
    action:
      - service: switch.turn_on
        entity_id: switch.pow

  - alias: Turn kitchen light off when no movement
    trigger:
    - entity_id: binary_sensor.motion_kitchen
      platform: state
      from: 'on'
      to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.pow

  - id: '1546613456223'
    alias: Turn light when there is movement
    trigger:
    - entity_id: binary_sensor.xiaomi_motion
      from: 'off'
      platform: state
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: '-02:00:00'
      - condition: sun
        before: sunrise
    action:
    - service: switch.turn_on
      entity_id: switch.sonoff_2
        
  - id: '1546615924808'
    alias: Turn light off after there is no movement
    trigger:
    - entity_id: binary_sensor.xiaomi_motion
      from: 'on'
      platform: state
      to: 'off'
    condition: []
    action:
    - service: switch.turn_off
      entity_id: switch.sonoff_2

  - id: '1546613458556'
    alias: 'Turn socket off on movement'
    trigger:
    - entity_id: binary_sensor.digoo_motion
      for:
        seconds: 15
      platform: state
      to: 'off'
    condition: []
    action:
      - service: switch.turn_off
        entity_id: switch.sonoff
          
  - id: '1546613458555'
    alias: Turn socket on movement
    trigger:
    - entity_id: binary_sensor.digoo_motion
      from: 'off'
      platform: state
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: '-02:00:00'
      - condition: sun
        before: sunrise
    action:
      - service: switch.turn_on
        entity_id: switch.sonoff