
sensor:
  - platform: min_max
    type: max
    name: Max Beacon A RSSI
    entity_ids:
      - sensor.xiaomi_amazfit_bip
      - sensor.xiaomi_mi_3
      - sensor.xiaomi_mi1

binary_sensor:
  - platform: trend
    sensors:
      bathroom_humidity_rising:
        entity_id: sensor.mijia_humidity
        friendly_name: Bathroom Humidity Rising
        sample_duration: 120
        min_gradient: 0.04
        max_samples: 5
      bathroom_humidity_falling:
        entity_id: sensor.mijia_humidity
        friendly_name: Bathroom Humidity Falling
        sample_duration: 120
        min_gradient: -0.01
        max_samples: 5

group:  
  multi_sensor_a:  
    name: Multi Sensor A  
    entities:  
      - sensor.humidity
      - sensor.temperature
      - sensor.multisensor_brightness
      - light.sensor_control_light
      - sensor.xiaomi_amazfit_bip
      - binary_sensor.xiaomi_amazfit_bip_presence
      - sensor.xiaomi_mi_3
      - binary_sensor.xiaomi_mi_3_presence
      - sensor.xiaomi_mi1
      - binary_sensor.xiaomi_mi1_presence

automation:
  - alias: Flash LED when there is a movement
    trigger:
    - entity_id: binary_sensor.pir_sensor, binary_sensor.pir_sensor_2
      from: 'off'
      to: 'on'
      platform: state
    action:
    - service: light.turn_on
      data_template: 
        entity_id: >
          {% if trigger.entity_id == 'binary_sensor.pir_sensor' %}
            light.sensor_control_light
          {% else %}
            light.sensor_control_light_2
          {% endif %}
        brightness: 255
        rgb_color: [255, 0, 0]

  - alias: Turn LED to normal state when no changes
    trigger:
    - entity_id: binary_sensor.pir_sensor, binary_sensor.pir_sensor_2
      from: 'on'
      to: 'off'
      platform: state
    action:
    - service: light.turn_on
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'binary_sensor.pir_sensor' %}
            light.sensor_control_light
          {% else %}
            light.sensor_control_light_2
          {% endif %}
        brightness: 20
        rgb_color: [0, 255, 0]