mqtt:
  # Remote controls
  # A - 2E1A22
  # B - 2E1A41
  # C - 9EEF31
  # D - 2E1A21
  binary_sensor:
    - name: "Remote Control A"
      state_topic: "home/remote-control-a"
      device_class: opening
      off_delay: 1

    - name: "Remote Control B"
      state_topic: "home/remote-control-b"
      device_class: opening
      off_delay: 1

    - name: "Remote Control C"
      state_topic: "home/remote-control-c"
      device_class: opening
      off_delay: 1

    - name: "Remote Control D"
      state_topic: "home/remote-control-d"
      device_class: opening
      off_delay: 1

automation:
  - id: remote-trigger-a-socket
    alias: "Toggle light on remote control"
    trigger:
      - entity_id: binary_sensor.remote_control_a
        platform: state
        to: "on"
    action:
      - service: light.toggle
        entity_id: light.sonoff_tv_light

  - id: remote-trigger-b-socket
    alias: "Toggle Jupiter room light on remote control"
    trigger:
      - entity_id: binary_sensor.remote_control_b
        platform: state
        to: "on"
    action:
      - service: light.toggle
        entity_id: light.jupiter_light

  - id: remote-trigger-c-socket
    alias: "Toggle central light on remote control"
    trigger:
      - entity_id: binary_sensor.remote_control_c
        platform: state
        to: "on"
    action:
      - service: switch.toggle
        entity_id: light.sonoff_stairs_light

  - id: remote-trigger-d-socket
    alias: "Toggle pavilion light"
    trigger:
      - entity_id: binary_sensor.remote_control_d
        platform: state
        to: "on"
    action:
      service: light.toggle
      entity_id: light.pavilion

  - id: ikea-remote-control-shortcut-light
    alias: "IKEA remote control shortcut TV light"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: tradfri_shortcut_button
          event: 1002
    action:
      - service: light.toggle
        entity_id: light.sonoff_tv_light
