sensor:
  - platform: mqtt
    state_topic: 'rpi-sensor/tele/STATE'
    name: 'Temperature Living Room'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temperature }}'

  - platform: mqtt
    state_topic: 'rpi-sensor/tele/STATE'
    name: 'Humidity Living Room'
    unit_of_measurement: '%'
    value_template: '{{ value_json.Humidity }}'

  - platform: mqtt
    state_topic: 'home/temperature-sensor-one'
    name: 'Temperature second'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'

  - platform: mqtt
    state_topic: 'home/temperature-sensor-one'
    name: 'Humidity second'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'

  - platform: mqtt
    state_topic: 'home/temperature-sensor-second'
    name: 'Temperature first'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'

  - platform: mqtt
    state_topic: 'home/temperature-sensor-second'
    name: 'Humidity first'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'