mqtt:
  sensor:
    - name: "Temperature Living Room"
      state_topic: "rpi-sensor/tele/STATE"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.Temperature }}"

    - name: "Humidity Living Room"
      state_topic: "rpi-sensor/tele/STATE"
      unit_of_measurement: "%"
      value_template: "{{ value_json.Humidity }}"

    - name: "Temperature second"
      state_topic: "home/temperature-sensor-one"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.temperature }}"

    - name: "Humidity second"
      state_topic: "home/temperature-sensor-one"
      unit_of_measurement: "%"
      value_template: "{{ value_json.humidity }}"

    - name: "Temperature first"
      state_topic: "home/temperature-sensor-second"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.temperature }}"

    - name: "Humidity first"
      state_topic: "home/temperature-sensor-second"
      unit_of_measurement: "%"
      value_template: "{{ value_json.humidity }}"

sensor:
  - platform: template
    sensors:
      water_leak_temperature:
        value_template: "{{ state_attr('binary_sensor.water', 'temperature') | float }}"
        device_class: temperature
        unit_of_measurement: "°C"
        friendly_name: "Water leak temperature"

  - platform: template
    sensors:
      xiaomi_motion_temperature:
        value_template: "{{ state_attr('sensor.xiaomi_motion', 'temperature') | float }}"
        device_class: temperature
        unit_of_measurement: "°C"
        friendly_name: "Xiaomi motion temperature"
